questions:
  - Một tính từ bằng tiếng Anh có nghĩa "tuyệt vời" trong slogan của Sun*
  - Format của sự kiện công nghệ của Sun* Hà Nội diễn ra trong tháng 10
  - Tên của core value xuất hiện trước Be Profressional
  - Chủ đề của cuộc thi công nghệ sắp tới diễn ra tại văn phòng HCM vào ngày 26/10
  - Tạp chí nội bộ của Sun* tên là gì
  - Năm 2019, văn phòng HCM đã đi du lịc với thành phố nào
  - Tên core value đầu tiên của Sun*
  - Tên của câu lạc bộ sức khỏe đầu tiên đã từng hoạt động tại văn phòng HCM
  - Tên 1 phòng họp tại văn phòng HCM
  - Format của sự kiện công nghệ sắp diễn ra tại văn phòng HCM vào ngày 26/10
  - Tên trang báo điện tử của Sun*
  - Đây là 1 vấn đề của dự án, đang được Sun* truyền thông mạnh mẽ về nhận thức để giảm thiểu vấn đề này, giúp cho dự án hoạt động hiệu quả
  - Tên sản phẩm website cuiar công ty mình, được biết đến là cộng đồng chia sẻ kiến thức công nghệ thông tin tại Việt Nam
  - Tên core value cuối cùng của Sun

answers:
  - _,_,_,_,A,W,E,S,O,M,E,_,_,_,_,_,_,_
  - _,_,_,_,_,H,A,C,K,A,T,H,O,N,_,_,_,_
  - _,_,_,_,G,O,F,A,S,T,_,_,_,_,_,_,_,_
  - _,_,_,_,_,L,O,S,T,I,N,T,H,E,M,A,Z,E
  - _,S,H,I,N,E,_,_,_,_,_,_,_,_,_,_,_,_
  - _,Q,U,Y,N,H,O,N,_,_,_,_,_,_,_,_,_,_
  - _,_,_,_,B,E,A,T,E,A,M,_,_,_,_,_,_,_
  - _,_,Y,O,G,A,_,_,_,_,_,_,_,_,_,_,_,_
  - _,_,_,E,A,R,T,H,_,_,_,_,_,_,_,_,_,_
  - _,_,_,_,C,T,F,_,_,_,_,_,_,_,_,_,_,_
  - S,U,N,*,N,E,W,S,_,_,_,_,_,_,_,_,_,_
  - _,I,N,C,I,D,E,N,T,_,_,_,_,_,_,_,_,_
  - _,_,V,I,B,L,0,_,_,_,_,_,_,_,_,_,_,_
  - _,_,S,T,A,Y,F,0,C,U,S,E,D,_,_,_,_,_

index: 5
